
stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_STRATEGY: clone
    GIT_SUBMODULE_FORCE_HTTPS: "true"
  script:
    - mkdir /tmp/$CI_JOB_NAME
    - make
    - cp -r /tmp/$CI_JOB_NAME $CI_PROJECT_DIR/$CI_JOB_NAME
    - rm -rf /tmp/$CI_JOB_NAME
  before_script:
    - rm -rf /tmp/$CI_JOB_NAME
  after_script:
    - rm -rf /tmp/$CI_JOB_NAME
  artifacts:
    paths:
      - $CI_JOB_NAME/
  tags:
    - testcluster


unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  needs:
    - job: build-job
  tags:
    - testcluster
  script:
    - cp -r build-job /tmp/build-job
    - cd /tmp/build-job/tests
    - make
    - make run