name: likwid-bench

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: info
      run: ls /sys/devices/system/cpu/cpu*/node*
    - name: make
      run: make
    - name: make test
      run: make test
    - name: help usage
      run: ./likwid-bench -h
